{{- $root := . }}
{{- range $configMap := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap.name }}
  namespace: {{ $root.Values.tenant }}
data:
  {{- range $key, $value := $configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
