apiVersion: v2
name: slinky-linky
description: A Helm chart for creating a new tenant of SlinkyLinky
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - tenant
  - multi-tenancy
maintainers:
  - name: Ramsay Domloge
sources:
  - https://github.com/rdomloge/sl-k8s-scripts
