apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-worker
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm-worker
      version: v1
  template:
    metadata:
      labels:
        app: helm-worker
        version: v1
    spec:
      # Only run on a node that has the image-builder role
      nodeSelector:
        node-role.kubernetes.io/image-builder: "true"
      containers:
        - name: helm-worker
          image: rdomloge/jenkins-worker-helm:1.0.0
          imagePullPolicy: Always
          env:
            - name: JENKINS_URL
              value: http://jenkins-service:8099
            - name: JENKINS_SECRET
              value: '[get from Jenkins secret in web UI]'
            - name: JENKINS_AGENT_NAME
              value: helm-worker
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent
            - name: JENKINS_AGENT_WORKDIR_ROOT
              value: /home/jenkins
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "1000m"
              memory: "256Mi"