apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-worker
  namespace: slinkylinky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-worker
      version: v1
  template:
    metadata:
      labels:
        app: spring-worker
        version: v1
    spec:
      containers:
        - name: spring-worker
          image: jenkins/jnlp-slave:4.3-4
          imagePullPolicy: IfNotPresent
          env:
            - name: jenkins_URL
              value: http://jenkins-service:8080
            - name: jenkins_SECRET
              value: CHANGEME
            - name: jenkins_AGENT_NAME
              value: spring-worker
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: spring-worker-home
              mountPath: /home/jenkins
      volumes:
        - name: spring-worker-home
          emptyDir: {}