apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-cors-header
  namespace: slinkylinky
spec:
  headers:
    customResponseHeaders:
      Access-Control-Allow-Origin: "*"

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist
  namespace: slinkylinky
spec:
  ipWhiteList:
    sourceRange:
      - 10.0.0.229
      - 88.215.1.114

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slinkylinky-ingress
  namespace: slinkylinky
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: slinkylinky-add-cors-header@kubernetescrd
    kubernetes.io/ingress.allow-http: "false"    
spec:
  rules:
    - host: rdomloge.synology.me
      http: &http_rules
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: adminwebsite-service
                port: 
                  number: 3000
          - path: /.rest/engagements
            pathType: Prefix
            backend:
              service:
                name: supplierengagement-service
                port: 
                  number: 8091
          - path: /.rest/auditrecords
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port: 
                  number: 8092
          - path: /.rest/stats
            pathType: Prefix
            backend:
              service:
                name: stats-service
                port: 
                  number: 8093
          - path: /.rest/mozsupport
            pathType: Prefix
            backend:
              service:
                name: stats-service
                port: 
                  number: 8093
          - path: /.rest/semrush
            pathType: Prefix
            backend:
              service:
                name: stats-service
                port: 
                  number: 8093
          - path: /.rest
            pathType: Prefix
            backend:
              service:
                name: linkservice-service
                port: 
                  number: 8090
  tls:
    - secretName: whoami-tls
      hosts:
        - rdomloge.synology.me
