apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Values.tenant }}
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: v1
  template:
    metadata:
      labels:
        app: postgres
        version: v1
    spec:
      containers:
        - name: postgres
          image: postgres:16.6
          imagePullPolicy: Always
          volumeMounts: 
            - name: sl-postgres-data
              mountPath: /var/lib/postgresql/data
          env:
            # This is needed to make PG put it's data in a subdirectory under the mounted volume, since Linode puts a 
            # lost+found directory at the root of the volume which PG doesn't like.
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_PASSWORD
              value: CHANGEME
          resources:
            requests:
              cpu: "1000m"
              memory: "600Mi"
            limits:
              cpu: "1500m"
              memory: "750Mi"
          ports:
            - containerPort: 5432
      volumes:
        - name: sl-postgres-data
          persistentVolumeClaim:
            claimName: sl-postgres-data-{{ .Values.tenant }}